'''
This is an utility script to debug images generated by the yolov7 dataset generation algorithm (a3_generate_yolov7.py)
Uses PIL to generate the image from the processed dataset and saves it to previews/preview-{stem}.png where stem is the name of the image
'''

import os
import random
from os.path import join as pjoin
import PIL
import PIL.ImageDraw
from PIL import Image

def load_lines(fn):
    with open(fn,"r") as f:
        lines =  f.read().split('\n')
        return [line for line in lines if len(line) > 1]

class_list_lines = load_lines("data/class_list.txt")
def convert_to_bboxes(label_txt,full_w,full_h):
    lines = load_lines(label_txt)
    def parse_line(line):
        cls_id, c_x, c_y, w, h = line.split()
        c_x = float(c_x)
        c_y = float(c_y)
        w = float(w) 
        h = float(h) 

        c_x *= full_w
        w *= full_w
        c_y *= full_h
        h *= full_h

        return class_list_lines[int(cls_id)], c_x- w/2, c_y - h/2, c_x + w/2, c_y + h/2
    parsed_lines = list(map(parse_line,lines))
    return parsed_lines

def draw_bbox(image_path,bboxes):
    im = Image.open(image_path)
    im = im.copy()
    draw = PIL.ImageDraw.Draw(im)
    for class_name, x0, y0, x1, y1 in bboxes:
        bbox = x0,y0,x1,y1
        draw.rectangle((x0,y0,x1,y1),outline="blue")
        text = class_name
        text_w, text_h = draw.textsize(text)
        text_x = bbox[0] + int(random.random()*(bbox[2]-bbox[1]))
        draw.rectangle((text_x, bbox[1], text_x + text_w, bbox[1] + text_h), fill="blue", outline="blue")
        draw.text((text_x, bbox[1]), text, fill=(0, 0, 0))
    return im

def do_all(stem,image_path,label_path):
    full_w, full_h = Image.open(image_path).size
    bboxes = convert_to_bboxes(label_path,full_w,full_h)
    im = draw_bbox(image_path,bboxes)
    im.show()
    if not os.path.exists("previews") and not os.path.isdir("previews"):
        os.mkdir("previews")
    im.save(f"previews/preview-{stem}.png")

data_dir = "data/splits/split-42-0.2-0.1/yolov7-42-0.2-0.1/"
mode = 'train'
images_dir = pjoin(data_dir,'images',mode)
labels_dir = pjoin(data_dir,'labels',mode)
stem = 'example_sim_layout_p_0_m_18_sw_0_7_s_1_0' # EDIT FILE HERE
# stem = os.listdir(images_dir)[0].split(".")[0] # SELECT RANDOM FILE
img = pjoin(images_dir,stem+'.png')
label_txt = pjoin(labels_dir,stem+".txt")
do_all(stem,img,label_txt)
print(stem)
# fn = "data/splits/split-42-0.2-0.1/test/marks/"+stem+".json"
# with open(fn,"r") as f:
#     print(f.read())