name: autogosling
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.4
  - onnxruntime=1.17
  - flask=3.0.2
  - flask-cors=4.0.0
  - pillow=10.2.0
  - opencv=4.9.0
  - requests=2.31.0
  - openai=1.12.0
  - python-dotenv=1.0.1